# 📌 과제 문제

## 1. 과제 목표
- medical 데이터를 활용한 데이터 분석 리포트 작성  
- 데이터를 확인하여 통계적 특징을 도출하고, 시각화와 함께 문제 해결 방안 제시  

---

## 2. 제출 내용

### 1) 분석 코드
- Python을 활용한 데이터 분석 코드 작성  
- 변수별 통계 분석, 상관관계 분석, 시각화 포함  

### 2) 분석 리포트
- 데이터 설명 (데이터 수, 변수 설명 - 각 변수의 의미, 데이터 타입 등)  
- 분석 코드 설명  
- 분석 결과 및 결론 설명 (변수별 통계 분석 결과, 변수 간 상관관계 분석, 시각화 결과 포함)  
- 문제 해결 방법 제안 (분석 결과를 기반으로 한 노쇼 원인 파악 및 개선 방안 제시)

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
medical = pd.read_excel('medical.xls')
medical

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,SMS_received,No-show
0,29900000000000,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,No
1,559000000000000,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,No
2,4260000000000,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,No
3,868000000000,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,No
4,8840000000000,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,No
...,...,...,...,...,...,...,...,...,...
65530,749000000000000,5606399,F,2016-04-20T10:13:04Z,2016-05-19T00:00:00Z,69,SÃO CRISTÓVÃO,0,No
65531,81200000000000,5603951,F,2016-04-20T07:32:19Z,2016-05-06T00:00:00Z,35,SÃO CRISTÓVÃO,1,Yes
65532,37400000000000,5605835,M,2016-04-20T09:31:06Z,2016-05-13T00:00:00Z,65,SÃO CRISTÓVÃO,0,Yes
65533,45145119925,5606859,F,2016-04-20T10:47:37Z,2016-05-20T00:00:00Z,78,SÃO CRISTÓVÃO,0,No
65534,4440000000000,5604571,M,2016-04-20T08:07:11Z,2016-05-06T00:00:00Z,1,SÃO CRISTÓVÃO,0,No

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,SMS_received,No-show
0,29900000000000,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,No
1,559000000000000,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,No
2,4260000000000,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,No
3,868000000000,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,No
4,8840000000000,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,No
...,...,...,...,...,...,...,...,...,...
65530,749000000000000,5606399,F,2016-04-20T10:13:04Z,2016-05-19T00:00:00Z,69,SÃO CRISTÓVÃO,0,No
65531,81200000000000,5603951,F,2016-04-20T07:32:19Z,2016-05-06T00:00:00Z,35,SÃO CRISTÓVÃO,1,Yes
65532,37400000000000,5605835,M,2016-04-20T09:31:06Z,2016-05-13T00:00:00Z,65,SÃO CRISTÓVÃO,0,Yes
65533,45145119925,5606859,F,2016-04-20T10:47:37Z,2016-05-20T00:00:00Z,78,SÃO CRISTÓVÃO,0,No
65534,4440000000000,5604571,M,2016-04-20T08:07:11Z,2016-05-06T00:00:00Z,1,SÃO CRISTÓVÃO,0,No